### ISSUE TITLE
2-3) 수정하신 부분

### ISSUE THREAD

**Issue by lameinthebox** [CheSangPark/ProgrammingLanguage#3]
https://github.com/CheSangPark/ProgrammingLanguage/blob/f13fd79c08a43507df06e3842635e49404285e0f/HW2/EX3.ml#L46-L49

 `NODE (1, 1, NODE (0, 3, EMPTY, EMPTY), NODE (0, 4, NODE (0, 5, EMPTY, EMPTY), EMPTY))`는 왼쏠힙이 맞는 것 같습니다.

**Comment by CheSangPark** [comment]
네 그림 그려보니까 맞았네요. 조만간 왼쏠힙 검증 함수도 올려 놓겠습니다.

**Comment by lameinthebox** [comment]
오..감사합니다.
